name: WIT

on: push

jobs:
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - run: SYSTEM=mac MACOSX_DEPLOYMENT_TARGET=11 make -C project wit
      - run: mv project/wit wit-macos-arm64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Latest
          files: wit-macos-arm64
