name: WIT

on: push

permissions:
  contents: write

jobs:
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - run: |
          alias cc=gcc-14
          alias c++=g++-14
          SYSTEM=mac MACOSX_DEPLOYMENT_TARGET=11 make -C project wit
          mv project/wit wit-macos-arm64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Latest
          files: wit-macos-arm64
  
  build-macos-x86_64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - run: |
          alias cc=gcc-14
          alias c++=g++-14
          SYSTEM=mac make -C project wit
          mv project/wit wit-macos-x86_64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Latest
          files: wit-macos-x86_64

  build-linux-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          SYSTEM=x86_64 SYSTEM_LINUX=1 make -C project wit
          mv project/wit wit-linux-x86_64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Latest
          files: wit-linux-x86_64

  build-windows-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          PRE="zig " CFLAGS=" -target x86_64-windows-gnu" make -C project wit
          mv project/wit.exe wit-windows-x86_64.exe
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Latest
          files: wit-windows-x86_64.exe
